name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.WORDPRESS_SECRETS }}

      - name: Deploy to server
        run: |
          # Add the SSH key to the known_hosts file to avoid host key verification issues.
          ssh-keyscan -H 15.206.173.55 >> ~/.ssh/known_hosts

          # Execute the deployment commands
          ssh ubuntu@15.206.173.55 'sudo su && cd && ls -la'
          # Additional deployment steps if needed
